version: "3.9"
networks:
  roboshop:
    driver: bridge
services:
  web:
    image: web:v2
    container_name: web
    ports:
    - "80:80"
    depends_on:
    - catalogue
    - mongodb
    - user
    - cart
  mongodb:
    image: mongodb:v2
    container_name: mongodb
  catalogue:
    image: catalogue:v2
    container_name: catalogue
    depends_on:
    - mongodb  
  user:
    image: user:v2
    container_name: user
    depends_on:
    - mongodb
    - redis
  redis:
    image: redis
  cart:
    image: vart:v2
    container_name: cart
    depends_on:
    - redis
    - catalogue      
