version: "3.9"
networks:
  roboshop:
    driver: bridge
volumes:
  mysql:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/ec2-user/mysql
  rabbitmq:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/ec2-user/rabbitmq
  redis:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/ec2-user/redis
  mongodb:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/ec2-user/mongodb   
        
services:
  web:
    image: web:v2
    container_name: web
    ports:
    - "80:80"
    depends_on:
    - catalogue
    - mongodb
    - user
    - cart
    - mysql
    - shipping
  mongodb:
    image: mongodb:v2
    container_name: mongodb
    volumes:
    - mongodb:/data/db
  catalogue:
    image: catalogue:v2
    container_name: catalogue
    depends_on:
    - mongodb  
  user:
    image: user:v2
    container_name: user
    depends_on:
    - mongodb
    - redis
  redis:
    image: redis
    container_name: redis
    volumes:
    - redis:/data
  cart:
    image: cart:v2
    container_name: cart
    depends_on:
    - redis
    - catalogue
  mysql:
    image: mysql:v2
    container_name: mysql
    volumes:
    - mysql:/var/lib/mysql
  shipping:
    image: shipping:v2  
    container_name: shipping
    depends_on:
    - mysql
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    volumes:
    - rabbitmq:/var/lib/rabbitmq
  payment:
    image: payment:v2
    container_name: payment
    depends_on:
    - rabbitmq
  rattings:
    image: ratings:v2 
    container_name: ratings
    depends_on:
    - mysql



  