version: "3.9"
networks:
  roboshop:
    driver: bridge
services:
  web:
    image: web:v2
    container_name: web
    ports:
    - "80:80"
    depends_on:
    - catalogue
    - mongodb
    - user
    - cart
    - mysql
    - shipping
  mongodb:
    image: mongodb:v2
    container_name: mongodb
  catalogue:
    image: catalogue:v2
    container_name: catalogue
    depends_on:
    - mongodb  
  user:
    image: user:v2
    container_name: user
    depends_on:
    - mongodb
    - redis
  redis:
    image: redis
  cart:
    image: cart:v2
    container_name: cart
    depends_on:
    - redis
    - catalogue
  mysql:
    image: mysql:v2
    container_name: mysql  
  shipping:
    image: shipping:v2  
    container_name: shipping
    depends_on:
    - mysql
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq  
  payment:
    image: payment:v2
    container_name: payment
    depends_on:
    - rabbitmq
  rattings:
    image: ratings:v2 
    container_name: ratings
    depends_on:
    - mysql



  