version: "3.9"
networks:
  project_robo:
    driver: bridge
services:
  web:
    image: web:v2
    container_name: web
    ports:
    - "80:80"
    depends_on:
    - catalogue
    - mongodb
    - user
    - cart
    - mysql
  mongodb:
    image: mongodb:v2
    container_name: mongodb
  catalogue:
    image: catalogue:v2
    container_name: catalogue
    depends_on:
    - mongodb  
  user:
    image: user:v2
    container_name: user
    depends_on:
    - mongodb
    - redis
  redis:
    image: redis
  cart:
    image: cart:v2
    container_name: cart
    depends_on:
    - redis
    - catalogue
  mysql:
    image: mysql:v2
    container_name: mysql
  shipping:
    image: shipping:v2
    container_name: shipping
    depends_on:
    - mysql    
